### ISSUE TITLE
how to use paginateArrayResults to limit product in category page.

### ISSUE THREAD

**Issue by dimasip** [Laracommerce/core#19]
CategoryController.php:
        return view('front.categories.category', [
            'category' => $category,
            'products' => $repo->findProducts()
        ]);

i want to change product limit in category just like in productcontroller.php below.

ProductController.php:
       return view('front.products.product-search', [
            'products' => $this->productRepo->paginateArrayResults($products->all(), 10)
        ]);

**Comment by morloderex** [comment]
This package is undergoing heavy development right now. And it's views are not a priority right now. We will get to it tho.

**Comment by jsdecena** [comment]
@dimasip This package is currently under development as what @morloderex said. 

But for your question, try this:

```
$products = $category->products;
$repo->paginateArrayResults($products->all(), 10);
```

**Comment by dimasip** [comment]
@jsdecena work like a charm, big thanks.
